### ISSUE TITLE
Installer un générateur de site statique

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2016#1]
@oncletom tu as une préférence entre Jekyll, Kirby, Metalsmith, ou autre ? 

Du moment qu'il y a une bonne doc et qu'on est assez libre sur notre workflow, moi ça m'ira très bien.

**Comment by thom4parisot** [comment]
Je serais bien parti sur du Jekyll, c'est simple et on a le deploy direct sur gh-pages.

**Comment by Twikito** [comment]
Ça me semble bien cool ce système ! Si je comprends bien, les pages peuvent être hébergées sur GitHub, mais la structure/css/assets, c'est où ?

**Comment by thom4parisot** [comment]
DTC -> []

Sur Github aussi ;-)

Cf. http://jekyllrb.com/docs/assets/ (donc Sass etc.)

**Comment by Twikito** [comment]
Pas mal du tout ! Par contre je me pose des questions niveau SEO sur l'url. Je vois mal comment garder l'url sudweb.fr si tout est hébergé sur GitHub. Je pense qu'il faudra une redirection 301 (surtout pas 302) vers sudweb.github.com (ou un truc du genre) et ça c'est pas bon.

**Comment by thom4parisot** [comment]
Reverse proxy (je vais faire un article dessus car c'est tout simple et super pratique).

Oublie pas que tu bosses avec des pros ;-)

(et en fait c'est exactement le cas du blog, cf https://github.com/sudweb/blog)

**Comment by DavidBruant** [comment]
> Par contre je me pose des questions niveau SEO sur l'url. Je vois mal comment garder l'url sudweb.fr si tout est hébergé sur GitHub.

Nein. CNAME my friend https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
Tu ne fais que découvrir Github, tu vas voir, c'est TRES TRES bien :-)

**Comment by DavidBruant** [comment]
@Twikito Aussi, tout Github est dispo via CDN via https://rawgit.com/ avec des headers CORS. Oui, monsieur ! Autant te dire que c'est du caviar en formation/cours ;-)

**Comment by thom4parisot** [comment]
@DavidBruant tu peux pas faire CNAME pour un sous-répertoire malheureusement :-( (sudweb.fr/2016 doit pointer vers sudweb.github.io/2016)

**Comment by DavidBruant** [comment]
Ah merde, oui, c'est vrai. My bad. hmm....
Idée : utiliser sudweb.github.io (donc CNAME) pour la dernière version du site et changer le nom du repo chaque année pour l'archivage. 
Ca demande juste de renommer un repo et recréer sudweb.github.io vide chaque année.

**Comment by thom4parisot** [comment]
Pas besoin avec un reverse-proxy ;-p
