### ISSUE TITLE
[Question] Génération du bundle JS

### ISSUE THREAD

**Issue by mabhub** [sudweb/2016#106]
Quelle est la méthode (outil) utilisée pour générer `main.min.js` et `main.min.js.map` ?
_(Pour pouvoir reproduire ce workflow et les re-générer de la même manière que la version initiale)_

**Comment by DirtyF** [comment]
Il me semble que Twikito utilise Prepros, nous n'avons pas encore intégré de worflow pour intégrer ça, mais tu as raison, un petit coup de npm serait de mise

**Comment by DirtyF** [comment]
@mabhub j'ai retrouvé la trace du fichier source pour main.js : https://github.com/sudweb/2016/blob/72b60aee3b2e2c6933004beeeb915617c10844c5/sources/js/main.js

**Comment by mabhub** [comment]
@DirtyF La source je l'avais bien, c'est bien le process / les paramètres pour passer au bundle qui manquent :)
