### ISSUE TITLE
301 pour HTTP → HTTPS

### ISSUE THREAD

**Issue by antoinentl** [sudweb/2016#128]
### Comportement constaté

HTTPS est implémenté sur le site web de Sud Web, toutefois certaines pages du site sont également consultables en HTTP (simple).
### Comportement attendu

Rediriger les requêtes HTTP (simple) vers HTTPS, par le biais d'une 301.
### Étapes pour reproduire le problème
1. se rendre sur une page en HTTP (simple), [celle-ci](http://sudweb.fr/2016/) par exemple ;
2. constater que la même page est consultable en HTTPS, [ici](https://sudweb.fr/2016/).

@sudweb/thym

**Comment by thom4parisot** [comment]
Bien vu @antoinentl !

En fait on avait un mix de `.htaccess` et de `ProxyPass` au niveau conf Apache donc la règle de redirect qui était configurée ne prenait pas le pas.

C'est réorganisé de sorte à ce que les règles soient appliquées avant la déclaration du proxy :-)

Merci !

```
$ curl --head -L http://sudweb.fr/2016/
HTTP/1.1 301 Moved Permanently
Date: Wed, 06 Apr 2016 20:06:09 GMT
Server: Apache/2.2
Location: https://sudweb.fr/2016/
Cache-Control: max-age=0
Expires: Wed, 06 Apr 2016 20:06:09 GMT
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
Via: 1.1 alproxy

HTTP/1.1 200 OK
Date: Wed, 06 Apr 2016 20:06:09 GMT
Server: GitHub.com
Content-Type: text/html; charset=utf-8
Last-Modified: Mon, 04 Apr 2016 11:58:13 GMT
Access-Control-Allow-Origin: *
Expires: Wed, 06 Apr 2016 19:52:46 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: B91F1216:2086:3015414:570566B0
Content-Length: 41739
Accept-Ranges: bytes
Age: 359
X-Served-By: cache-lcy1129-LCY
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1459973169.652048,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 51c83c846804ae54adbf3b975b741614d2e366ef
X-UA-Compatible: IE=Edge,chrome=1
Strict-Transport-Security: max-age=16070400;
Via: 1.1 varnish, 1.1 alproxy
```

**Comment by DavidBruant** [comment]
:+1: sur le `Strict-Transport-Security` ;-)
