### ISSUE TITLE
Les liens vers les sites des intervenants sont automatiquement en HTTPS

### ISSUE THREAD

**Issue by antoinentl** [sudweb/2016#142]
### Comportement constaté

Les liens (URLs) des sites des intervenant-e-s sont générés automatiquement en HTTPS (sauf pour [Chris Lowis](http://blog.chrislowis.co.uk/), le chanceux ;) ), malheureusement (mais c'est comme cela) la plupart des sites web des intervenants n'ont pas d'accès en HTTPS, ou n'ont pas implémenté de certificat.  
Le résultat : des pages "La connexion n'est pas sécurisée" (ou autre selon le navigateur utilisé) pour la plupart des sites.
### Comportement attendu

Afficher les sites web des intervenant-e-s selon la technologie utilisée (pas forcément HTTPS).
### Étapes pour reproduire le problème
- se rendre sur [cette page](https://sudweb.fr/2016/) ;
- cliquer sur une URL d'un-e intervenant-e ([exemple 1](https://www.stefanieposavec.co.uk/), [exemple 2](https://www.redisdead.net/), [exemple 3](https://www.souffrance-et-travail.com/), etc.) ;
- constater les pages d'_erreur_ : "La connexion n'est pas sécurisée".

@sudweb/thym

**Comment by DirtyF** [comment]
merci @antoinentl il vaut en effet toujours mieux préfixer les URLs : http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by antoinentl** [comment]
De rien ! Et merci pour la ressource !
