### ISSUE TITLE
Les avatars Twitter sont bloqués sur mobile

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2016#156]
### Comportement constaté

Manque l'image de super-héros masculin sur 
https://sudweb.fr/2016/participants/
### Comportement attendu

De magnifiques avatars de super-héros encapés.
### Étapes pour reproduire le problème
- Aller sur https://sudweb.fr/2016/participants/
- Ne pas voir les avatars, mais trouver le texte alternatif clair
- Saisir un ticket parce qu'on n'a qu'un mobile et donc pas la possibilité de cloner pour corriger soi-même
- Envoyer des messages d'encouragement pour la dernière ligne droite

@sudweb/thym

**Comment by DirtyF** [comment]
@borisschapira hmm on a eu ça avec des extensions qui bloquent Gravatar, mais sur mobile, c'est space.

**Comment by borisschapira** [comment]
Chrome sur Android…

**Comment by borisschapira** [comment]
Aaah, mea culpa, se sont les avatars custos qui ne passent pas sur Chrome et Brave mais qui passent sur Firefox. Les vignettes de super-héros passent. Je me suis fait avoir par le texte alternatif.

**Comment by DirtyF** [comment]
OK vu merci @borisschapira, nous allons donc devoir récupérer les avatars en cache. cc/ @oncletom

**Comment by thom4parisot** [comment]
C'est vrai qu'on pourrait en faire une copie locale lors de la génération du site, pas con du tout !

**Comment by borisschapira** [comment]
Le problème vient de Twitter :
Sur Desktop, https://twitter.com/borisschapira/profile_image?size=bigger t'amène vers https://pbs.twimg.com/profile_images/522372287614291968/h9zEViOp_bigger.jpeg. Avec un User-Agent mobile, ça t'amène sur https://mobile.twitter.com/borisschapira/profile_image?size=bigger => 404.

**Comment by borisschapira** [comment]
Testé à l'instant sur Chrome Desktop Max OS X en "Device mode" iPhone 5.
