### ISSUE TITLE
Documenter le projet

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2016#3]
Pointé par @oncletom, [Neat](http://neat.bourbon.io/) devrait nous suffire :
- facile à prendre en main :cake: ,
- grille personnalisable :pencil2: ,
- définition des breakpoints :hammer: ;
- nombreux mixins :sparkles: ,
- [x] documentation :book: 

Dans un deuxième temps, comme suggéré par @bertrandkeller on peut aussi utiliser Jekyll pour documenter les composants. (cf. https://mademistakes.com/articles/jekyll-style-guide/)

**Comment by thom4parisot** [comment]
Tu confirmes Mr @kaelig ? Ou vaut mieux qu'on utilise le framework Salesforce ? ;-)

**Comment by kaelig** [comment]
Vu la taille du projet je sais pas si ça vaut le coup d'utiliser un framework Sass. 

Un petit `npm install sass-mq` et une passe d'autoprefixer devrait faire l'affaire. Pour la grille, là par contre je ne sais que recommander car ça dépend vraiment des besoins.

**Comment by bertrandkeller** [comment]
La [DILA](http://www.dila.premier-ministre.gouv.fr/) veut maintenant construire la doc de son "framework" avec Jekyll. Et je pense qu'ils seront à Sud Web.

**Comment by thom4parisot** [comment]
@bertrandkeller tu peux aussi les pointer vers [readthedocs.org](https://readthedocs.org/).
