### ISSUE TITLE
soucis de typo sur mobile

### ISSUE THREAD

**Issue by Natouille** [sudweb/2016#39]
### Comportement constaté

La police Squada One ne s'affiche pas sur mobile
### Comportement attendu

La police Squada One est bien chargée sur mobile
## 
- 

@sudweb/thym

**Comment by DirtyF** [comment]
@yannkozon Pourrais-tu préciser ton environnement (Appareil, Version de l'OS, Navigateur) ?

**Comment by yannkozon** [comment]
Désolé du retour, c'était mon adblocker sur ios :/

**Comment by DirtyF** [comment]
@yannkozon non c'est intéressant, bon à savoir, merci.

**Comment by yannkozon** [comment]
En modifiant la typo safe ça devrait régler le problème.

**Comment by thom4parisot** [comment]
@DirtyF on la charge depuis un CDN ou autre ?

**Comment by DirtyF** [comment]
@oncletom depuis Google Fonts :  
https://github.com/sudweb/2016/blob/gh-pages/_includes/head.html#L17

mais mauvaise typo safe :
https://github.com/sudweb/2016/blob/gh-pages/_sass/_variables.scss#L82

je fais une PR cc/ @Twikito
