### ISSUE TITLE
Lier vers le site perso si il existe

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2016#42]
Afin d'éviter de générer une hostilité bien regrettable chez @notabene
Un lien vers le site perso de l'orateur est présent s'il existe

**Comment by notabene** [comment]
Huhu.

Pour l'historique :

> Je reste assez hostile à l'idée, pour donner le pedigree des gens, de lier vers leur profil Twitter plutôt que leur site perso. @SudWeb
> https://twitter.com/notabene/status/705313733778776064

Pas hostile à SudWeb, dis donc ;)

**Comment by thom4parisot** [comment]
@notabene tu penses que le site Web est plus neutre ? S'ils n'ont pas de site web, twitter en fallback te parait correct ?

**Comment by notabene** [comment]
@oncletom Tout à fait, et ce que vous avez fait me semble très bien (moins _one-platform-specific_).

Merci les copains. :)

**Comment by DirtyF** [comment]
@notabene share the love :heart: , share the web :globe_with_meridians:
