### ISSUE TITLE
Bon boulot

### ISSUE THREAD

**Issue by davidbgk** [sudweb/2016#49]
### Comportement constaté

Le site est lisible et j'en apprécie le ton.
### Comportement attendu

Que le site soit lisible et que j'en apprécie le ton.
### Étapes pour reproduire le problème
- ouvrir http://sudweb.fr/2016
- sourire
- il n'y a pas de point 3

@sudweb/thym

**Comment by DirtyF** [comment]
Merci @davidbgk :heart_eyes: 

Tes gènes sont à jamais inscrites dans l'ADN de Sud Web, tu le sais, et ce n'est pas un hasard si certains sujets abordés cette année résonnent encore avec la quête de sens, à laquelle tu nous invitais en 2013. Nous continuons de porter le flambeau.

@sudweb/thym

**Comment by thom4parisot** [comment]
![](http://tclhost.com/WxAZLY0.gif)
