### ISSUE TITLE
Impossible de consulter le site avec iOS 7.1.2

### ISSUE THREAD

**Issue by 7studio** [sudweb/2016#51]
### Comportement constaté

Il est impossible de consulter le site Sud Web avec un appareil sous iOS 7.1.2.
Le problème a été constaté avec deux appareils différents (iPhone 4 et iPad Air) via Safari et l'app. Twitter.

![photo](https://cloud.githubusercontent.com/assets/835430/13498952/795274c2-e15c-11e5-8816-86c5d16011b4.PNG)
### Comportement attendu

Que le site soit consultable.
### Étapes pour reproduire le problème
- ouvrir http://sudweb.fr/2016 avec un appareil sous iOS 7.1.2.

@sudweb/thym

**Comment by Twikito** [comment]
Je pense que la solution va se trouver ici.
http://caniuse.com/flexbox

**Comment by DirtyF** [comment]
@Twikito c'est le plugin autoprefixer qui n'est pas appliqué sur Github Pages, pour le moment on va ajouter les prefixes manquants direct dans le Sass, on verra avec @oncletom pour le support des plugins en publiant directement le site compilé plus tard.

Désolé pour la mauvaise expérience @7studio :/

**Comment by oncletom** [comment]
@7studio #59 devrait avoir résolu ton problème. Tu confirmes ? :-)

**Comment by DirtyF** [comment]
@7studio à priori ça vient des SVG, j'ai le même problème sur mon Iphone 4. Safari n'a pas l'air d'appliquer le viewbox et affiche le sprite en entier. Vu le peu de visites (1%) et notre difficulté pour débugguer, ça va être difficile pour @Twikito de proposer un correctif.

Ah, c'est compliqué le développement web !

**Comment by DirtyF** [comment]
@7studio toujours aucune amélioration en ajoutant les doctypes XML et les espaces de nom :sob:

**Comment by dascritch** [comment]
Il vaut mieux indiquer min-width, min-height, max-width et max-height. Effectivement, webkit considérait que par défaut, il appliquait  soit une dimension nulle, soit une dimension égale à tout le viewport.

**Comment by 7studio** [comment]
Merci pour tes retours @DirtyF Si le nombre de visiteurs n'est pas significatif, on laisse tomber. J'ai juste pas de chance :relieved:

Désolé de ne pas trouver le temps de chercher une solution de mon côté :disappointed_relieved:

**Comment by DirtyF** [comment]
@7studio je suis aussi dans ton cas, on va tester les retours de @dascritch

**Comment by fvsch** [comment]
Le premier suspect c'est le non-support des  `<use xlink:href="/mon/super/sprite.svg#mon-symbole"></use>` avant iOS 8.1. Je vois que vous utilisez [svgxuse](https://github.com/Keyamoon/svgxuse). Est-ce que ce polyfill gère correctement iOS 7? Est-ce que [svg4everybody](https://github.com/jonathantneal/svg4everybody) s'en sortirait mieux?

Ensuite si le problème est lié au dimensionnement via viewBox, j'avoue que je ne l'utilise jamais. Fixer des dimensions par défaut en CSS marche bien en général:

``` css
.icon {
  width: 1em;
  height: 1em;
}
```

quitte à les redéfinir ensuite.
Et perso j'éviterais les `height: auto`, à tout hasard.
