### ISSUE TITLE
La billetterie n'apparait pas lorsqu'on bloque les scripts de sites tiers

### ISSUE THREAD

**Issue by clochix** [sudweb/2016#55]
### Comportement constaté

La billetterie n'apparait pas lorsqu'on bloque les scripts de sites tiers.
![Ce qu'on voit](https://cloud.githubusercontent.com/assets/384908/13512517/7902a890-e19b-11e5-943c-aa532d8c6f3c.png)
### Comportement attendu

Voir la billetterie.
### Étapes pour reproduire le problème
- uMatrix est une extension relativement répandue chez les paranoïaques, qu'ils utilisent [Firefox](https://addons.mozilla.org/fr/firefox/addon/umatrix/) ou [Chromium](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf?hl=fr). Par défaut, elle bloque tous les contenus issus de sites tiers ;
- installer l'extension uMatrix ;
- consulter le site ;
- arpenter la page à la recherche de la billetterie ; 

Peut-être y a-t-il moyen de détecter que la billetterie n'est pas affichée et de demander à l'internaute de désactiver ses divers bloqueurs de contenus tiers.

**Comment by thom4parisot** [comment]
Si on incluait la billetterie via une iframe, ça fonctionnerait ? Est-ce que du coup `<noscript>` serait pris en charge ? Si uMatrix bloque la création de scripts et non l'inclusion de ressources distantes ça pourrait le faire.

Le lien que tu vois "billetterie weezevent" est le lien "alternatif" proposé par le widget Weezevent. En le cliquant tu arrives sur la page de commande … mais bon, idéalement on est dac qu'on voudrait l'avoir incorporé dans la page.

**Comment by clochix** [comment]
Par défaut, je crois que uMatrix bloque tous les contenus de sites tiers, sauf les CSS et les images. Donc je doute qu'utiliser une iFrame change grand chose.

Javascript est activé et les scripts du domaine exécutés, donc je doute également qu'on puisse faire quelque chose avec noscript.

Le lien alternatif point vers https://www.weezevent.com//?c=sys_widget, où rien n'indique comment accéder à votre page spécifique.

Mais ne t'embête pas trop, les utilisateurs de uMatrix sont habitués à le désactiver lorsqu'une page réagit étrangement.

**Comment by DirtyF** [comment]
@clochix :  sinon https://www.weezevent.com/sudweb-2016 si ton extension préfère ?

**Comment by clochix** [comment]
Merci ☺
En fait, il suffit de mettre le site en liste blanche dans uMatrix pour que le composant weezevent s'affiche correctement dans la page. Le seul souci est que si on ne s'aperçoit pas que quelque chose a été bloqué par uMatrix, on ne pense pas tout de suite à ça.

**Comment by DirtyF** [comment]
C'est gentil de nous faire confiance, au plaisir de te voir à Bordeux :)

**Comment by thom4parisot** [comment]
Yep t'as raison @clochix ; on peut mettre un texte plus explicite sur le lien (genre *Oups, la billetterie n'arrive pas à se charger, merci de suivre ce lien pour l'ouvrir dans une nouvelle fenêtre").

Au moins ça serait plus indicatif que le texte actuel.

**Comment by Natouille** [comment]
Pour info, j'ai le même problème avec Privacy Badger de l'EFF, par défaut il bloque Weezevent

**Comment by mabhub** [comment]
Le _"blocage de <u>scripts</u> de sites tiers"_ est résolu en partie par #104  (en incluant le script de Weezevent en local), mais reste la problématique du blocage d'`iframe`.
