### ISSUE TITLE
Formulaire https dans une page http

### ISSUE THREAD

**Issue by mabhub** [sudweb/2016#56]
### Comportement constaté

Le navigateur produit un [avertissement](http://i.snag.gy/WNdcv.jpg) de non sécurisation de la connexion au formulaire de paiement.
### Comportement attendu

Full https ! ;)

J'ai bien vu que le formulaire de paiement est dans une `iframe` qui est bien https. Mais cela rassurera sans doutes quelques utilisateurs s'ils ne se retrouvent pas confrontés à ce genre d'avertissement de non sécurisation. [Letsencrypt](https://letsencrypt.org/) permet de créer un certificat rapidement et gratuitement.
### Étapes pour reproduire le problème
- Avoir enregistré, dans son navigateurs, les données de saisie d'une carte de paiement.
- Passer le tunnel d'achat de billet Sudweb jusqu'à l'étape de paiement.
- Commencer à saisir une numéro de carte de paiement.

**Comment by DirtyF** [comment]
merci @mabhub pour ce retour. Pour info nous sommes hébergés par Github Pages qui supporte https :
https://sudweb.github.io/2016/, tu peux passer par là si tu veux éviter l'avertissement :)

Pour info nous utilisons un mécanisme de proxy reverse qui redirige les requête de sudweb.fr vers Github. Nous sommes hébergés à la base chez Alwaysdate, et en effet on pourrait [y installer des certifs](http://www.cosmiclatte.fr/blog/passer-a-https-avec-lets-encrypt/).

Qu'en penses-tu @oncletom ?

**Comment by DavidBruant** [comment]
Ca serait mieux indeed. Une fois que vous êtes en HTTPS, n'oubliez pas d'activer les headers HSTS https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security

**Comment by thom4parisot** [comment]
Ça n'a rien à voir avec le fait qu'on utilise GitHub pages, ne mélangeons pas tout.

Question @mabhub : l'iframe est en HTTPS mais le fait qu'elle soit incluse dans une page en HTTP désactive cette feature d'autocomplétion de CB ? Et on est d'accord que ça n'affecte que l'autocomplétion de la recopie du numéro de CB, pas la transaction elle-même ?

**Comment by mabhub** [comment]
@oncletom Oui, je pense que seule l’auto-complétion est impactée, et qu'effectivement la transaction, elle, reste safe.

Par contre, puisqu'en JS on peut normalement accéder aux documents des frames enfants, un JS de la page principale _pourrait_ aller recopier des contenus saisis à l'intérieur de l'`iframe` (À vérifier si le https ajoute une restriction à ça ou non), puis donc les faire transiter sur http.

**Comment by thom4parisot** [comment]
C'est juste. Avec CSP j'imagine qu'on peut prévenir l'injection de scripts pour éviter qu'ils tripatouillent le contenu de la frame — et ça veut dire faire confiance au domaine sudweb.fr :-)

@DirtyF signale qu'AlwaysData fait des mouvements pour basculer vers de l'automatisation de génération de certificats SSL via Let's Encrypt (cf. http://forum.alwaysdata.com/viewtopic.php?id=4631) donc on va surement s'orienter vers ça.

**Comment by DirtyF** [comment]
:heart: @alwaysdata :heart:
