### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mabhub** [sudweb/2016#57]
Un Dockerfile à la racine du projet pourrait permettre de créer un conteneur incluant toutes les dépendances d'environnement de développement, et de servir le site en local sans imposer d'installation (autre que docker).

**Comment by DirtyF** [comment]
@mabhub Tu pourrais proposer une PR avec un README détaillé pour qu'on regarde si c'est vraiment plus simple ou pas pour les contributeurs de la @sudweb/thym ?

**Comment by mabhub** [comment]
Ouep, je tenterai ça (il est probable même que je tente directement de faire le Dockerfile).

**Comment by DirtyF** [comment]
:ok_hand:

**Comment by thom4parisot** [comment]
C'est une bonne idée. Si ça peut inclure le nécessaire pour développer en local c'est encore mieux.
Car on installe tout le bazar uniquement faire du dev avant de pousser le site statique en ligne.

**Comment by mabhub** [comment]
Proposition de Dockerfile faite ici : https://github.com/sudweb/2016/pull/64
