### ISSUE TITLE
Dans l'appli d'inscription, on ne peut pas tabuler dans le champ "pays"

### ISSUE THREAD

**Issue by julienw** [sudweb/2016#61]
### Comportement constaté
1. Aller à l'inscription.
2. Mettre le curseur dans "Ville".
3. Tabuler pour aller dans "Pays"
   => Le curseur va dans "Téléphone mobile"
### Comportement attendu

Le curseur va dans Pays.

**Comment by DirtyF** [comment]
@julienw Yep, nous dépendons de @Weezevent pour cette partie. 
En espérant qu'ils voient ton retour et qu'ils puissent corriger.
