### ISSUE TITLE
Images de fond sur mobile

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2016#70]
### Comportement constaté

On ne distingue pas la totalité de l'image de fond des bannières sur mobile (testé sur un Iphone / IOS 7)

![banner-1](https://cloud.githubusercontent.com/assets/138627/13634526/fe25c4de-e5ed-11e5-9769-41c8ca48f71c.png)
### Étapes pour reproduire le problème
- Consulter le site sur un téléphone mobile  

cc/@Twikito

**Comment by Twikito** [comment]
J'avais oublié ce bug&hellip;
Le problème vient des `background-attachement: fixed` combinés aux `background-size: cover`.

Sur Android, c'est pas compliqué, l'arrière plan fixé n'est pas interprété. Donc pas de problème.

Par contre sur iOS, Safari fait encore ch*** parce, oui, il interprète l'arrière plan fixé, mais combiné à la taille qui recouvre le parent, l'arrière plan prend alors la taille du viewport. N'importe quoi !
Ceci dit, c'est peut-être pour cette raison que les développeurs de chez Google et Firefox ont décidé de ne pas interpréter l'arrière plan fixé sur navigateur mobile : pour ne pas faire nawak.

J'ai donc deux choix.

Soit je décide de mettre cet arrière plan fixed uniquement sur navigateur desktop, ce qui pourrait impliquer de détecter les touchscreens via Modernizr, mais la team dit que [ce n'est pas possible](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/). Il faut considérer également que certains écrans desktop ont aussi le touchscreen.

Dans ce cas peut être définir une largeur minimum, mais laquelle ? L'iPhone 6 a une dimension de viewport de 375px x 667px ce qui implique de prendre la plus grande pour le cas de consultation en paysage. Ça fait déjà bien grand. Mais l'iPad Pro fait une dimension de viewport de 1024px x 1366px, ce qui couvre déjà pas mal de dimensions desktop.

A l'heure actuelle je ne vois pas de méthode correcte et pérenne de détecter les navigateurs mobile. Une `@media` mobile serait vraiment appréciée !

Donc pour le moment, je supprime cet effet d'arrière plan fixé au scroll. Merci Safari -_-v

**Comment by Twikito** [comment]
Ou alors je trouve que cet effet apporte quelque chose, et je limite la casse aux viewports sous 640px ?
Ça laisserait l'iPhone 6 paysage, et les iPads.
