### ISSUE TITLE
Participants manquants

### ISSUE THREAD

**Issue by mabhub** [sudweb/2016#84]
### Comportement constaté

Il manque certains participants (moi par exemple ^^') alors que bien présent dans les données.

Je pense que c'est lié au filtre `uniq: "name"` qui dédoublonne le tableau des attendees mais donc ne conserve qu'un seul `ticket_type`. Et si par exemple le seul doublon restant a l'id `667250`.. il saute.

@sudweb/thym

**Comment by mabhub** [comment]
Peut-être que la solution serait d'enlever les objets avec le `ticket_type: 667250` directement du json de base (plutôt que de filtrer à l'affichage), ou encore de fusionner ceux ayant des `name` identiques en amont (plutôt que dédoublonner à l'affichage).

Autre possibilité : voir s'il est possible de trier sur un second critère après le classement alphabétique par `name`, pour faire en sorte que les occurrences avec le `ticket_type: 667250` n'apparaissent pas en premier, et donc ne soit pas les seuls restante après le `uniq`.

**Comment by DirtyF** [comment]
:smile:  hello super @mabhub rapide comme l':zap: 

Je te rassure tu es bien présent, et en supér-héros incognito. 

![capture d ecran 2016-03-12 02 04 40](https://cloud.githubusercontent.com/assets/103008/13719505/f5349bb0-e7f6-11e5-8575-9ff69f449726.png)

D'ailleurs vu que tu t'es inscrit à différents tarifs, tu apparaissais même trois fois au début, d'où le `uniq`. J'ai commenté pour le moment le filtre par tarif donc tous les participant sont présents : orateurs, participants, thym members.

Il manque simplement les réservations, car par défaut l'API de Weezevent ne les affiche pas.

**Comment by thom4parisot** [comment]
Si c'est juste ça on peut inclure les réservations dans les résultats.

Vu que le filtre était fait sur les tickets orateurs, je ne vois pas pourquoi @mabhub aurait été masqué, malgré l'utilisation d'`uniq`.

**Comment by DirtyF** [comment]
@oncletom réservations ajoutées dans https://github.com/sudweb/2016/commit/6ab23378050d928b5e7bce4545de57114a2bca5e

**Comment by Natouille** [comment]
Moi je ne vois pas @mabhub et je ne vois aucun avatar

**Comment by thom4parisot** [comment]
C'est parce que #79 n'est pas mergée (on va pouvoir bientot)

**Comment by mabhub** [comment]
Alors après recherche avec un bisect, ce qui résout réellement le problème que je présentais initialement, c'est 033c5d1f3e8dc3a13dccd3f525a1f4615a1d6f78 (qui fait bien partie de #79) qui change le `ticket_type` exclu de l'affichage `667250` (soirée) par `701385`. _(Et que donc ce que j'essaiyais d'expliquer, c'est que le `uniq` ne laissait dans mon cas que l'objet avec le `ticket_type` soirée que le `if` faisait ensuite sauter)_

Donc comme dit @oncletom, ce ticket peut-être fermé une fois #79 fusionné.

**Comment by DirtyF** [comment]
@mabhub hop c'est fait : http://sudweb.fr/2016/participants/
