### ISSUE TITLE
Changement de photo (pas critique)

### ISSUE THREAD

**Issue by nico3333fr** [sudweb/2016#96]
Bonjour,
### Comportement constaté

j'ai vu que vous aviez utilisé le gravatar de mon adresse gmail pour la liste des participants...
### Comportement attendu

serait-il possible d'utiliser cette photo à la place ?  https://www.flickr.com/photos/parisweb/22170758586/in/album-72157659898836715/
### Étapes pour reproduire le problème

Afficher la liste des participants :)

Au plaisir,
Nico

@sudweb/thym

**Comment by DirtyF** [comment]
@nico3333fr dans l'immédiat si cette photo est associée à une autre adresse mail du type nico+avatar@gmail.com sur Gravatar, ça sera plus simple.

Voir aussi #97 pour une solution plus générique

**Comment by nico3333fr** [comment]
Alors, tu peux essayer contact (at) nicolas-hoffmann.net ça devrait le faire ;)

**Comment by DirtyF** [comment]
@nico3333fr done http://sudweb.fr/2016/participants/

**Comment by nico3333fr** [comment]
@DirtyF Great!

![mercredi](https://cloud.githubusercontent.com/assets/2578321/13818403/07d9ca54-eb96-11e5-8e80-247614a55a12.gif)
